### PR TITLE
Removal of 1 item topics 

### PR DESCRIPTION
**Pull request by clmedders**
## Summary

This PR will remove topic pages that are tagged once. 

### Preview

[Link to Preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/cm-removal-1-topics/)

### Solution
1. delete all references of topics within files from the front matter 
2. delete the topic from the topics folder 
3. run hugo to check that site builds 
4. added removed links to the web archive for future reference

### How To Test

1. refer to the spreadsheet, and anything that has a note that it is tagged once check that the URL is not longer active for that landing page. See Trello ticket for spreadsheet using this [Link as the base](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/cm-removal-1-topics/)
2. also can pull down branch and run the following tests `hugo` and then `npm run lint:json`

---

### Dev Checklist

- [x] PR has correct labels
- [x] A11y testing (voice over testing, meets WCAG, run axe tools)
- [x] Code is formatted properly

### CODE REVIEW

**Review by bonnieAcameron — APPROVED** [review]
Looks good!

**Review by mejiaj — COMMENTED** [review]
@clmedders good work on tackling all these topics.

The solution doesn't mention submitting the original landing pages to the [web archive](https://web.archive.org). Was that done?

Minor suggestion, commit messages are currently numbered. It would help if you added a little detail, for example:

```bash
# Instead of numbered; adding a small note
commit 2 → Remove animal and plant health topic
```

---

Also, are there preview links for this? Should we remove or what should a tester visit to confirm?

**Comment by clmedders** [comment]
@mejiaj 
yes, the links were added to the web archive! I will be sure to add that to the solution in the future. 

Good point on the commit message I think my plan for that was to number so I could know if I needed to pull which was the most recent but makes sense to add the files changed as well 

Good find on the testing... my thought was to use the preview as the base and then add the slug from the spreadsheet to visit the URL I will move that link down in the commands for better finding

**Review by nick-mon1 — CHANGES_REQUESTED** [review]
## What I Tested

Compared the tags tab spreadsheet with the github topic files removed to find which topics weren't deleted.

## How I Tested:

### Spreadsheet Filters

**71** topics listed in spreadsheet

action: "delete"
notes: "Agency tag; 1 item tagged.", "Program tag; 1 item tagged", "1 item tagged", "Content type; 1 item tagged."

### Topics Deleted in PR

**64** topics removed on PR

Missing topics:

- [x] bia
- [ ] ies
- [ ] ihs
- [ ] nasm
- [ ] nida
- [ ] ntia
- [ ] ntis

Tested these topics locally and they still display 1 tagged item.

**Review by bonnieAcameron — APPROVED** [review]

**Review by nick-mon1 — APPROVED** [review]
Looks good, thanks @clmedders.

**Review by ToniBonittoGSA — APPROVED** [review]

**Pull request merged**
