### PR TITLE
7/10: Accessibility for teams

### PR DESCRIPTION
**Pull request by jeremyzilar**
## HOLD till July 10

**Doc:** https://docs.google.com/document/d/1zGgafRMhk2rT6MMatD9_u3v5du-C_4Rh1s062n0tUEM/edit 

**Preview:** 
homepage: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/accessibility-for-teams/
post: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/accessibility-for-teams/2018/07/10/introducing-accessibility-for-teams/ 

_Image will be provided by @thisisdano_

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
@thisisdano here's the image to upload, thx!

accessibility post keyboard-access

**Comment by thisisdano** [comment]
Added image as `accessibility-keyboard-access`

**Comment by maya** [comment]
I'm not seeing the image that @ToniBonittoGSA uploaded https://github.com/GSA/digitalgov.gov/pull/662#issuecomment-401922973 in the post preview. Should I be?

**Comment by ToniBonittoGSA** [comment]
@maya you should be able to see it now; I updated the links in the first comment

**Comment by maya** [comment]
It looks like there are 2 merge conflicts in `data/top6.yml` that need to be resolved @thisisdano @ToniBonittoGSA

**Pull request merged**
