### PR TITLE
Update logo please

### PR DESCRIPTION
**Pull request by mhotch24**
Please replace the old logo {{< img-right src="challenge-gov-logo" >}} with the one here: challenge-gov-new-logo

This PR implements the following **changes:**

* insert your summary of your request here, add more bullets as needed

**URL / Link to page**

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
Hi @mhotch24 

We need to receive this new logo in the following dimensions as **.png** files:

- 1200 x 630
- 600 x 600

thanks!

**Comment by mhotch24** [comment]
Hi Toni,
Please find the new logos attached.

Thank you!

MARNI HOTCHKISS, QQE-C

Senior Manager,

Creative Direction + UX

***@***.***

(888) 527-8488 x 714



<https://www.kaptivategroup.com/>

<https://www.linkedin.com/company/kaptivate-llc>
<https://www.facebook.com/KaptivateGroup/>
<https://twitter.com/KaptivateLLC>
<https://www.instagram.com/kaptivategroup/>

#PivotAndThrive

**Comment by mhotch24** [comment]
Hi Toni. Please find the new images attached. Thank you!
1200x630
600x600

**Comment by ToniBonittoGSA** [comment]
Fixing in https://github.com/GSA/digitalgov.gov/pull/4372

**Pull request closed without merging**
