### PR TITLE
Data Cabinet Community Page

### PR DESCRIPTION
**Pull request by jeremyzilar**
## From: https://github.com/GSA/digitalgov.gov/issues/523

A new community page for the Data Cabinet

**Preview:** https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/data-cabinet-community/

Communities page: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/data-cabinet-community/communities/ 
Data Cabinet page: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/data-cabinet-community/communities/data-cabinet/

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar 

The inconsistency of the name is odd & may be confusing to users (referring to the CoP as both "Data Cabinet" and "Federal Data Science Community of Practice")

A user gets "Data Cabinet" as: 

 - the link text on the [Communities](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/data-cabinet-community/communities/) page, 
 - then as the [new page URL](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/data-cabinet-community/communities/data-cabinet/), 
 - and as new page title at top of the page

but then the next line, the 1st paragraph of copy has, "Welcome to the Federal Data Science Community of Practice," while the 2nd paragraph has, "The Data Cabinet plays an essential role in advancing data-driven management, maximizing the use of the data, and enhancing problem-solving throughout government" -- without explaining who/what this Data Cabinet is. 

By using a different name, most users might think the Data Cabinet is a different group, and/or wonder why the first line says _Welcome to Federal Data Science CoP_, and not _Welcome to the Data Cabinet_. 
 ~ their [website](https://www.ntis.gov/thedatacabinet/) is confusing as well; when you visit, it has, "Welcome to the Federal Data Science Community of Practice" but "Data Cabinet" in the logos and footer")

Can we change the intro from

> Welcome to the Federal Data Science Community of Practice 🎉
> 
> We serve as the principal community of practice for data professionals across federal government to share proven best practices and critical insights into what’s working “on the front lines” in agencies. The Data Cabinet plays an essential role in advancing data-driven management, maximizing the use of the data, and enhancing problem-solving throughout government.

to:

> Welcome to the Federal Data Science Community of Practice 🎉
> 
> We serve as the principal community of practice for data professionals across federal government to share proven best practices and critical insights into what’s working “on the front lines” in agencies. Also known as _The Data Cabinet_, the community plays an essential role in advancing data-driven management, maximizing the use of the data, and enhancing problem-solving throughout government.

and the very last line from:

> Learn more about the Data Cabinet at: https://www.ntis.gov/thedatacabinet/

to:

> [Visit our website](https://www.ntis.gov/thedatacabinet/) to learn more about our mission and download our publications.

**Comment by ToniBonittoGSA** [comment]
If so, on https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/data-cabinet-community/communities/ 

Change

> Data Cabinet: A community for data professionals across federal government to share proven best practices and critical insights.
> Learn more »

to: 

> "Data Cabinet": The Federal Data Science Community of Practice is for data professionals across federal government to share proven best practices and critical insights.
> Learn more »

**Comment by ToniBonittoGSA** [comment]
@JacquelineSnee @jeremyzilar is the email body text incorrect (subscribe FCPCCS)?

[**listserv@listserv.gsa.gov**](mailto:listserv@listserv.gsa.gov?subject=&amp;body=subscribe%20FCPCCS)

**Comment by jeremyzilar** [comment]
All good points @ToniBonittoGSA 👍

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar I don't know about replacing it ~ even they call it the _Federal Data Science Community of Practice_ on their site

Unfortunately, on their website, they don't explain this "The Data Cabinet" name either.. A cabinet is a body of high-ranking officials, typically consisting of the top leaders of the executive branch. Is this something the White House had a hand in creating, or is this just a nickname for the Community of Practice to sound/appear more "official"?

**Comment by jeremyzilar** [comment]
I am pretty sure this community is led by high-ranking officials out of the White House, and thus a cabinet. I will confirm with them over email.

Either way, I think we need to aim for names and descriptions of communities that are as clear as possible.

**Comment by JacquelineSnee** [comment]
Agree! AND if we have communities around the same topic like “data” what
makes them different is even more important. Cuz why have two communities
that do the same thing especially if the audience is the same.

Sent from my iPhone

On Mar 29, 2018, at 6:55 AM, Jeremy Zilar <notifications@github.com> wrote:

I am pretty sure this community is led by high-ranking officials out of the
White House, and thus a cabinet. I will confirm with them over email.

Either way, I think we need to aim for names and descriptions of
communities that are as clear as possible.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GSA/digitalgov.gov/pull/534#issuecomment-377242964>,
or mute
the thread

**Comment by ToniBonittoGSA** [comment]
Yes, @JacquelineSnee, @jeremyzilar  ~ I was wondering if we should group them under a Data heading

**Data**:

- **[Data Cabinet](#)**&mdash;The Federal Data Science Community of Practice is for data professionals across the federal government to share proven best practices and critical insights.
**[Learn more »](#)**

- **[Open Data](#)**&mdash;Uniting open data leads at federal agencies, data stewards, and all others in government interested in open data, enterprise data inventory, civic tech, and data-driven government issues.
**[Learn more »](#)**

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA I think we'll eventually want to group things under headings. We should hold off on doing that till there are more to group, since this is the only one.

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA Here is a new preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/data-cabinet-community/communities/data-cabinet/

Your edits were very helpful and on point. I combined your edits with the edits by the Data Center team

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar @JacquelineSnee 

a 2nd person has okayed this update -- shall we approve and go live?

**Pull request merged**
