### PR TITLE
Update 2020-07-16-uswds-monthly-call-july-2020.md

### PR DESCRIPTION
**Pull request by DanielJPino-ux**
updating description and time of the July 2020 USWDS webinar

This PR implements the following **changes:**

* updating  the time of the webinar to correct time
* updating the description of the webinar with correct copy

### CODE REVIEW

**Comment by DanielJPino-ux** [comment]
@ToniBonittoGSA  and @saracope  - the federalist build isn't showing - could you review?

**Comment by saracope** [comment]
@DanielJPino-ux This had a couple of extra lines of code at the beginning of the file which threw off the Hugo build. I removed that so it should be ok now.

**Comment by DanielJPino-ux** [comment]
The build looked good - though when I checked the "register" link it did not show the correct link which should be: https://www.eventbrite.com/e/uswds-monthly-call-form-components-update-tickets-112126128268

**Comment by DanielJPino-ux** [comment]
https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/July-2020-USWDS-Event/event/2020/07/16/uswds-monthly-call-july-2020/

the build was successful and linked to the appropriate registration url

**Pull request merged**
