### PR TITLE
Event Page: YouTube chat + Video Embed fixes

### PR DESCRIPTION
**Pull request by jeremyzilar**
Re: https://github.com/GSA/digitalgov.gov/issues/544

### Event Listings
- Events listing will now show the events that occurred on the same day, even if they were in the morning.
- Fixed link to **"All Events"** on Federalist previews
- added the ability for event pages to have `chatbox: false` which will hide the chatbox from an event page

### Upcoming events
- video is directly embedded
- chat box is directly embedded and visible _(chatbox will ONLY work on the live site)_
- **Preview:** https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/YouTube-Chat-embed-fix/event/2018/04/05/creating-videos-in-languages-other-than-english/

### Past events
- video is embedded with an image/overlay
- chat box is removed
- **Preview:** https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/YouTube-Chat-embed-fix/event/2018/03/14/infographics-plain-language-considerations/

### CODE REVIEW

**Comment by jeremyzilar** [comment]
Just so you know, the Chat Box will ONLY show up on the LIVE site. It needs to be on the `www.digitalgov.gov` domain to work.

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar @jthalls 
the Upcoming one https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/YouTube-Chat-embed-fix/event/2018/04/05/creating-videos-in-languages-other-than-english/ 
looks OK on desktop, but not on mobile: 

img_0038

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar @jthalls 
Past events https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/YouTube-Chat-embed-fix/event/2018/03/14/infographics-plain-language-considerations/ 

looks the same (good) on both desktop and mobile: 

img_0039

**Comment by jeremyzilar** [comment]
Good catch @ToniBonittoGSA that white space you are seeing there, that is the chatbox that wont appear on the preview links, but will appear on the LIVE url. It'll appear on mobile :)

**Pull request merged**
