### PR TITLE
fix search support email

### PR DESCRIPTION
**Pull request by jimkreft**
## Summary

A potential search.gov user has been attempting to reach out to us via the old search.gov support email that he found on digital.gov.  This fixes the search.gov support email across the digital.gov footprint.

## Preview

[Link to Preview]()

## Solution

I changed search@support.digitalgov.gov to search@gsa.gov

## How To Test

Confirm that the search.go support email has been changed from search@support.digitalgov.gov to search@gsa.gov

### CODE REVIEW

**Comment by jimkreft** [comment]
fixes #7815

**Review by bonnieAcameron — APPROVED** [review]

**Review by nick-mon1 — DISMISSED** [review]
### What I Tested

- [x] checked for any outstanding `search@support.digitalgov.gov`
- [x] ran locally to confirm new email address is displayed in email client

**Comment by jimkreft** [comment]
Thanks for the quick review!

**Review by ToniBonittoGSA — APPROVED** [review]
Removed bio, all looks good

**Comment by ToniBonittoGSA** [comment]
CodeQL build error here; fixed in https://github.com/GSA/digitalgov.gov/pull/7816

**Pull request closed without merging**
