### PR TITLE
Update checklist-of-requirements-for-federal-digital-services.md

### PR DESCRIPTION
**Pull request by RachelF**
This PR implements the following **changes:**

Adding a new checklist (yes, an actual Excel checklist, see attached) for the "checklist" page. 
I suggest linking in the first sentence of the "overarching policies" section - but maybe it would work better in the Note? Or as a separate bullet? Please add in whatever way makes the most sense for you.
Update includes some minor language tweaks to the new FOIA section.

REALLY NEW version - **updated 10/22** after co-working session (use this one): 
[Go-Live Checklist for Federal Websites and Digital Services (v1.0).xlsx](https://github.com/GSA/digitalgov.gov/files/7400956/Go-Live.Checklist.for.Federal.Websites.and.Digital.Services.v1.0.xlsx)

Includes the following changes:
- added version number
- on overview tab, moved cells with links from column A to B, so the "click" area for links shows within the main cell and is easier to navigate/click.
- removed the "implementation guidance" (row 3) on every topic page
- doublechecked all links to ensure each cell that contains a link 1) has only one link, and 2) the link points to where it's supposed to
- adjusted font for all cells that were in "calibri" font (changed to Arial, because PublicSans is not available in excel)

### CODE REVIEW

**Comment by afeijoo** [comment]
LGTM!

**Comment by ToniBonittoGSA** [comment]
Great! The spreadsheet has to uploaded via [another system](https://github.com/GSA/digitalgov.gov/wiki/Uploading-Files) we set up here in GitHub; will do that then circle back here

**Comment by ToniBonittoGSA** [comment]
Great, thanks, @RachelF! 

The spreadsheet has to be uploaded via another system we set up here in GitHub, but before we get to that, I need to fully review and make some plain language corrections (the guidelines say to not use a forward slash `/` in place of words, use of internal shorthand/jargon, etc.)

Also, has this already been reviewed for accessibility?

thx!

**Comment by RachelF** [comment]
@ToniBonittoGSA I did review it for accessibility. It will likely return one color contrast error b/c I added a lookup table at the bottom of one of the tabs using white text/white background. It's not something that users should be interacting with or need to see, but it's used to populate the dropdowns. I locked those cells as well. What do you think, will that be OK?

**Comment by ToniBonittoGSA** [comment]
> @ToniBonittoGSA I did review it for accessibility. It will likely return one color contrast error b/c I added a lookup table at the bottom of one of the tabs using white text/white background. It's not something that users should be interacting with or need to see, but it's used to populate the dropdowns. I locked those cells as well. What do you think, will that be OK?

Hi @RachelF 
I don't know how Excel files work in that regard (calculations, accessibility) .. I'll post in the Help Wanted channel to see if someone can take a look

**Comment by RachelF** [comment]
@ToniBonittoGSA I also reached out to our 508 team to see if they can provide some guidance, will let you know what they say.

**Comment by RachelF** [comment]
[Go-Live Checklist for Federal Websites and Digital Services.xlsx](https://github.com/GSA/digitalgov.gov/files/6984776/Go-Live.Checklist.for.Federal.Websites.and.Digital.Services.xlsx)
@ToniBonittoGSA I've done quite a bit of remediation on this to improve accessibility, it should be good to publish now. (Please delete the first version I sent over and use this one instead.) LMK if you have any questions!

**Comment by RachelF** [comment]
@ToniBonittoGSA Just to be sure... I had Mark Buchko from GSA IT/508 team review the spreadsheet and he has cleared it for publication. I'm reattaching to ensure you have the latest version, cleared by Mark as 508-compliant.
[Go-Live Checklist for Federal Websites and Digital Services.xlsx](https://github.com/GSA/digitalgov.gov/files/7079587/Go-Live.Checklist.for.Federal.Websites.and.Digital.Services.xlsx)

**Review by ToniBonittoGSA — APPROVED** [review]

**Pull request merged**
