### PR TITLE
Update service_challengegov.md

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
updated 2 of 3 broken links; couldn't find new page/URL on Challenge.gov: 

> Read about how federal challenges improved the lives of these winning [problem-solvers](https://www.challenge.gov/success-stories/).

---

**Preview:** 
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/digitalgov.gov/ND-broken-links/services/challenge-gov/

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar As usual, I clicked federalist's Details for the preview link.. When I got to the main Services page and clicked for the Challenge.gov page, I got this, 
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/services/challenge-gov/?dg (`/preview/gsa/digitalgov.gov/ND-broken-links/` is missing from the URL)

instead of https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/digitalgov.gov/ND-broken-links/services/challenge-gov/ 
I got

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA — can we move your content changes over to @twgsa16's PR https://github.com/GSA/digitalgov.gov/pull/1880/files and close this, since she made edits over there?

**Comment by jeremyzilar** [comment]
Also fixed the permalink issue you found in a separate PR https://github.com/GSA/digitalgov.gov/pull/1885

**Comment by ToniBonittoGSA** [comment]
Will do, thanks!

**Pull request closed without merging**
