### PR TITLE
New default page design

### PR DESCRIPTION
**Pull request by jeremyzilar**
### What was improved
- added breadcrumb navigation to pages
- added three distinct divs within `.entry` — `.entry-head`, `.entry-content`, `.entry-meta`
- set `.entry` width to `650px` on desktop
- adjusted the styles for mobile to allow for smoother reading experience on all devices
- created an `entry.css` file for all styles relating to `.entry`
- adjusted the spacing for list-items on all pages and posts
- added "Last Updated" text, indicating when the last commit to this page was made
- linked the "Last Updated" text to the commit history page for that file.
- added "Feedback" text, giving readers the ability to email feedback on a specific page

### Preview links
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/
- Resources: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/
- Services: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/
- U.S. Digital Registry: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/u-s-digital-registry/
- About: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/about/
- Community page: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/communities/multilingual/

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
Howdy.. 

# Universal:

- it's ok to use 'feedback'?
- remove hyphen on email (Examples: in _Have feedback on this page? Send us an e-mail »_ on all pages, and in Contact Us at end of [About page](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/about/))
- always hide email addresses in links to help reduce spam (example: "Send us an e-mail digitalgov@gsa.gov" under Contact Us at end of [About page](https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/about/)  needs an edit)
- Header tags have to be sequential for screen readers, and should not skip numbers for size/weight formatting (the Multilingual page goes from 1 to 3 to 5). 
Title is always 1; in copy, start with 2 for main sections and goes down under each H2 from there. 
On https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/communities/multilingual/ 
**Join** and **Who We Are** should be H2
**Multilingual Websites and Digital Channels–Standards**, and **Guidelines, Research and Mandates, Translation/Adaptation/Localization of Content**, and **Marketing, Outreach, Education, Training** should be H3s


---
# About page:

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/about/ 

- remove italics on Standards URL
- we have _send us an email_ on the page 3 times; at least 1 should go.

I don't know that the last 2 bullets
> - Create an issue on GitHub
> - Or make an edit to our pages and submit a pull request

fit well under **Contact Us**, 

For the Issue bullet, link should be on all text, like 'send an email' (Cognitive: verbs [send, create, visit, open, learn, etc.] should always be linked if the action takes the user to another page or launches an application like an email client)

Change last bullet to something like: 
Make an edit and submit a pull request in GitHub using the Edit button at the end of every page. 
 or
Want to update a page and submit a pull request for us to review in GitHub? Use the Edit button at the end of any page.

but.. maybe the 2 GitHub items should go elsewhere? Is it conflicting to have "Have feedback on this page? Send us an e-mail »" right below 'make an edit' info?

Maybe change that to

_Not familiar with GitHub yet? [Send us a page update via email »](digitalgov@gsa.gov)_

**Question**: Can we set subject line in markdown email links? would help filter msgs coming in to DG's account.

(apologies if this part was a little rambly.. if unclear, let me know)

---
# Breadcrumbs:

## 1 - missing level on 2 Resource sub-pages; example:  
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/negotiated-terms-of-service-agreements/ 

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/agency-points-of-contact-for-federal-compatible-terms-of-service-agreements/

Both should have: 
[Resources](https://www.digitalgov.gov/resources/) / [Federal Terms of Services Agreements](https://www.digitalgov.gov/resources/federal-compatible-terms-of-service-agreements/)

## 2 - missing level on 4 Service sub-pages; example:  
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/dap/common-questions-about-dap-faq/ 

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/dap/analytics-tool-instructions/ 

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/dap/guidance-for-dap-gov-wide-data/ 

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/dap/incorporating-the-digital-analytics-program-tool-into-your-agencys-metric-program/ 

All should have: 
[Services](https://www.digitalgov.gov/services/) / [Digital Analytics Program](https://www.digitalgov.gov/services/dap/)
or
[Services](https://www.digitalgov.gov/services/) / [DAP](https://www.digitalgov.gov/services/dap/)


## 3 - incorrect Open Opps breadcrumbs
Note: _Open Opps_ was only placed under _Join DigitalGov_ because adding it to the menu in the WordPress/Solostream template broke the menu layout. 

**Main**
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/join-digitalgov/open-opportunities-in-digitalgov/

has 
Home / Join-digitalgovs
should not have text (see # 4 below)

_Note_: Having 2 of Open Opps' 4 sub-pages in a different section (now in Resources) is confusing; breadcrumbs are not consistent: 

**Sub-page**
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/join-digitalgov/open-opportunities-in-digitalgov/how-open-opportunities-works/ 

has
Home / Join-digitalgovs
Should be
[Open Opportunities](https://www.digitalgov.gov/join-digitalgov/open-opportunities-in-digitalgov/)

**Sub-page**, not originally in Resources
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/open-opportunities-task-creator-toolkit/ 

has
Home / Resources
Should be
[Open Opportunities](https://www.digitalgov.gov/join-digitalgov/open-opportunities-in-digitalgov/)

**Sub-page** of Task Creator Toolkit, not originally in Resources
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/open-opportunities-task-creator-toolkit/10-tips-for-creating-the-perfect-open-opportunity-task/ 

has
Home / Resources
Should be
[Open Opportunities](https://www.digitalgov.gov/join-digitalgov/open-opportunities-in-digitalgov/) / [Task Creator Toolkit](https://www.digitalgov.gov/resources/open-opportunities-task-creator-toolkit/)

**Sub-page**
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/join-digitalgov/open-opportunities-in-digitalgov/open-opportunities-terms-of-use/

has
Home / Join-digitalgovs
Should be
[Open Opportunities](https://www.digitalgov.gov/join-digitalgov/open-opportunities-in-digitalgov/)

## 4 - Keep breadcrumb line, but no need for breadcrumb text

Goes to consistent layout/alignment, and we have Home links in the nav menu and on the logo; this would be a 3rd one above the fold. 

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/digitalgov-university/

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/communities/

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/about/

https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/join-digitalgov/ 

Join has
Home / Etcs
Etcs link goes to 404 page

## 5 - breadcrumb typo, change in hierarchy

Policies page (link only in footer)
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/about/policies/ 

has
Home / Abouts

Note: The new About page doesn't mention policies; should we remove from /about/ 'folder', and [also] not have breadcrumb? (see # 4 above)

**Comment by jeremyzilar** [comment]
**Header tags** — The change that this PR focuses on is the page design that surrounds and supports the body copy. Any heading changes within the copy will need to be changed on a page by page basis in the cleanup process.

**Comment by jeremyzilar** [comment]
**About page** — The change that this PR focuses on is the page design that surrounds and supports the body copy. 

@ToniBonittoGSA Can you put this in a new About Page issue and I can address that as well?

**Comment by jeremyzilar** [comment]
**Breadcrumbs** — most of the issues you bring up here are things that we will need to address in the cleanup. Not in the design of the page.

Though it should be noted that as part of this change, the pages (files) will need to be organized in a slightly new way to make the breadcrumbs function.

This will mean that we'll need to move root pages out of the folder and into the parent.
For example: `/content/resources/resources.md` will need to move to `/content/resources.md` for it to have just `Home` in the breadcrumb nav and not `Home / Resources`. Same for services.

Here is how it would roughly work:

📁 Content
- 📄 resources.md
- 📁 Resources
    - 📁 dap
        - 📄 overview.md
        - 📄 templates.md
    - 📄 dap.md
- 📁 Services
- 📄 services.md

**Comment by jeremyzilar** [comment]
In talking with @ToniBonittoGSA, she suggested that we not move the index files outside of the folder, instead, move the files within and rename them to `index.md`.

So, the `/resources/` folder will contain all of the resource pages, but the main resources page/file will be the `index.md` file.

Giving that a try now.

**Comment by ToniBonittoGSA** [comment]
I was thinking of directory structure, to help with the breadcrumbs (and file organization in general).. like

/resources/
and under that would be:

1) the main "[Resources](https://www.digitalgov.gov/resources/)" file/page as index.md
2) sub-folders for Resource pages that have sub-page groupings; like /Terms of Service/
3) any individual resource pages that don't belong to a group, like the [Checklist page](https://www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/) and [Contact Center Guidelines](https://www.digitalgov.gov/resources/contact-center-guidelines/)

Then, the /Terms of Service/ sub-folder would have:

1) the main TOS file/page ([Federal-Compatible Terms of Service Agreements](https://www.digitalgov.gov/resources/federal-compatible-terms-of-service-agreements/)) as index.md
2) and the individual sub-page files: [Negotiated Terms of Service Agreements](https://www.digitalgov.gov/resources/negotiated-terms-of-service-agreements/) and [Agency Points of Contact for Federal Compatible Terms of Service Agreements](https://www.digitalgov.gov/resources/agency-points-of-contact-for-federal-compatible-terms-of-service-agreements/) 


** and similar for DAP under /services/

**Comment by jeremyzilar** [comment]
I fixed the way the breadcrumbs work to reflect @ToniBonittoGSA's spec above.

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar I clicked the Details link for the new build ~ am seeing the same breadcrumb as yesterday on the 3 TOS pages (am I looking in the right spot?)
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/federal-compatible-terms-of-service-agreements/ 
 -- https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/negotiated-terms-of-service-agreements/ 
 -- https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/agency-points-of-contact-for-federal-compatible-terms-of-service-agreements/

**Comment by jeremyzilar** [comment]
Yes, that is correct. 

The parent-child relationships reflected in the breadcrumbs will not reflect the hierarchy till we clean up the individual pages. That is being fixed in https://github.com/GSA/digitalgov.gov/pull/254

**Comment by ToniBonittoGSA** [comment]
Ahh, ok - thx

**Comment by jeremyzilar** [comment]
There is an issue with the build. I am looking into it.

---

I had changed the `resources.md` file to `index.md`. And it looks like those files might need to be `_index.md` according to the HUGO docs. Trying that out now

**Comment by jeremyzilar** [comment]
This has moved on to a new Pull Request: https://github.com/GSA/digitalgov.gov/pull/256

**Pull request merged**
