### PR TITLE
test commit for federalist image paths

### PR DESCRIPTION
**Pull request by nick-mon1**
This PR implements the following **changes:**

Related to issue 4895

### CODE REVIEW

**Comment by nick-mon1** [comment]
Digital.gov and the federalist build use the same directory path (`/uswds/img/usa-icons-bg/search--white.svg`) for the `search--white.svg` icon.

Recent [federalist build](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/nl-image-paths/) implements updated hugo path: `Search` and still returns a 404.

Logs shows `2022-05-23 15:53:48 INFO [publish] Uploading preview/gsa/digitalgov.gov/nl-image-paths/uswds/img/usa-icons-bg/search--white.svg
` is uploaded to proper location.

Maybe this needs to be moved to `/img` or this is federalist caching issue?



Screen Shot 2022-05-23 at 10 37 05 AM
Screen Shot 2022-05-23 at 10 37 33 AM

**Review by mejiaj — COMMENTED** [review]
Is the overall recommendation to use relative paths? The search in header looks good in Federalist, but there are still a few missing images when I browse through the top-level pages.

[Guides and Resources](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/nl-image-paths/resources/)

image

Newsletter signup in footer
image

**Comment by nick-mon1** [comment]
Fixed the search bar for the `/resources` page.
The `/img/love-letter.png` path is set in the [css background property](https://github.com/GSA/digitalgov.gov/blob/a5dd258936f489f178ac2daba5f46497b1437eaf/themes/digital.gov/src/scss/new/_newsletter-signup.scss#L48), will need to consider how to refactor for federalist builds.

1. Newsletter markup is rendered with a hubspot form, will need further assistance with identifying how to update the path this way
2. Not a good practice to include hugo code in css
3. Create an environment variable to fix this loading path in federalist

**Review by mejiaj — APPROVED** [review]
@nick-mon1 can you fix conflicts? Otherwise LGTM, thank you.

**Review by ToniBonittoGSA — APPROVED** [review]

**Pull request merged**
