### PR TITLE
DRAFT: Results-Oriented Accountability for Grants

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
New CoP page from Jacob

Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/ToniBonittoGSA-patch-1/communities/results-oriented-accountability-for-grants/

### CODE REVIEW

**Comment by jeremyzilar** [comment]
What is the text in the middle for?
```
- Govvies
- Rest
```

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar just placeholders.. Jacob said they'll have 2 lists

**Comment by ToniBonittoGSA** [comment]
Hi @jeremyzilar 

@jpgsa  sent image for this page; I can add later.. thx!

pma logo_hi res_3_12final-03

**Comment by jeremyzilar** [comment]
The summary on this page is not very clear. There is a lot of jargon in it.

```
Our community engages stakeholders around the President’s Management Agenda (PMA), and the Results-Oriented Accountability for Grants Cross-Agency Priority (CAP) Goal.
```

- describe "stakholder" in non-jargon terms
- can we describe "the Results-Oriented Accountability for Grants Cross-Agency Priority (CAP) Goal" without using the words `the Results-Oriented Accountability for Grants Cross-Agency Priority (CAP) Goal`
- does "President’s Management Agenda (PMA)" have to be mentioned in the first sentence?

**Comment by jpgsa** [comment]
@jeremyzilar 
The content questions above are good regarding jargon. I've asked @ToniBonittoGSA to ask them if there is a way to clarify. However, I expect they will need approvals to change the info. I'd like for us to launch and then let them update post-launch. 
Thanks!

**Pull request merged**
