### PR TITLE
Create Event “2020/10/2020-10-01-plain-language-summit-2020”

### PR DESCRIPTION
**Pull request by ayerkes**
Automatically generated by Netlify CMS

https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/cms/events/2020/10/2020-10-01-plain-language-summit-2020/event/2020/10/27/plain-language-summit-2020/

### CODE REVIEW

**Review by ayerkes — COMMENTED** [review]
another edit to the event page.

**Review by ayerkes — COMMENTED** [review]
Removed the speakers who don't have their grat service agreements in yet.

**Review by ayerkes — COMMENTED** [review]
adding back Ginny Reddish.

**Review by ayerkes — COMMENTED** [review]
adding in plain language quotes

**Review by ayerkes — COMMENTED** [review]
Cleaning up the event page.

**Review by saracope — APPROVED** [review]

**Pull request merged**
