### PR TITLE
Create Blog Post “2021/02/2021-02-08-call-for-participation-2021-government-ux-summit”

### PR DESCRIPTION
**Pull request by Gabr1elleKING**
Automatically generated by Netlify CMS

### CODE REVIEW

**Review by Gabr1elleKING — COMMENTED** [review]
Created UX Summit call for participation via News/Blog post. Redirected old page to correct content type.

**Review by Gabr1elleKING — COMMENTED** [review]
Attempt 2

**Review by Gabr1elleKING — COMMENTED** [review]
Added slug

**Review by Gabr1elleKING — COMMENTED** [review]
Edit #2

**Review by ToniBonittoGSA — APPROVED** [review]

**Pull request merged**
