### PR TITLE
New events: Making a Mobile-Friendly Website Using the ADAPT Model

### PR DESCRIPTION
**Pull request by RhettSkelton**
Learn how to improve the user experience of your website by following the ADAPT Model to enhance the performance of your content on cellular networks or mobile devices.

A one-line description of the changes you're making and how they'll affect users.

---

**Preview:** 
https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/digitalgov.gov/master-1/event/2020/02/25/making-a-mobilefriendly-website-using-adapt/

### CODE REVIEW

**Comment by RhettSkelton** [comment]
I'm having an issue with this build in federalist. Initially, I thought that my HTML code in the build was causing issues, so I converted it to Markdown, but the error still persists. Below is the error log.

2020-02-13 02:34:05 INFO [main] Running build for gsa/digitalgov.gov/master-1
**2020-02-13 02:34:05 ERROR [clone-repo] Cloning into '/work/site_repo'...**
2020-02-13 02:34:18 INFO [clone-repo] Cleaning /work/site_repo
2020-02-13 02:34:18 INFO [clone-repo] Cloning gsa/digitalgov.gov/master-1 to /work/site_repo
2020-02-13 02:34:18 INFO [clone-repo] Cleaning /work/site_repo/_site
2020-02-13 02:34:19 INFO [run-federalist-script] Node version: v10.19.0
2020-02-13 02:34:20 INFO [run-federalist-script] NPM version: 6.13.4
2020-02-13 02:34:29 INFO [run-federalist-script] Installing production dependencies in package.json
2020-02-13 02:34:29 INFO [run-federalist-script] > puppeteer@1.20.0 install /work/site_repo/node_modules/puppeteer
2020-02-13 02:34:29 INFO [run-federalist-script] > node install.js
2020-02-13 02:35:13 INFO [run-federalist-script] Chromium downloaded to /work/site_repo/node_modules/puppeteer/.local-chromium/linux-686378
**2020-02-13 02:35:15 ERROR [run-federalist-script] npm WARN digitalgov.gov@2.0.0 No license field.**
2020-02-13 02:35:15 INFO [run-federalist-script] added 159 packages from 96 contributors in 53.696s
2020-02-13 02:35:20 INFO [build-hugo] .hugo-version found
2020-02-13 02:35:20 INFO [build-hugo] Using hugo version in .hugo-version: 0.60.1
2020-02-13 02:35:20 INFO [build-hugo] Downloading hugo version 0.60.1
2020-02-13 02:35:20 INFO [build-hugo] hugo version: Hugo Static Site Generator v0.60.1-96066756 linux/amd64 BuildDate: 2019-11-29T14:57:23Z
2020-02-13 02:35:22 INFO [build-hugo] Building site with hugo
2020-02-13 02:35:22 INFO [build-hugo] Building sites …
2020-02-13 02:35:23 INFO [build-hugo] Total in 865 ms
**2020-02-13 02:35:23 ERROR [build-hugo] Error: Error building site: "/work/site_repo/content/events/2020/02/2020-02-25-making-a-mobilefriendly-website-using-adapt.md:18:1": failed to unmarshal YAML: yaml: line 17: found unexpected end of stream**
**2020-02-13 02:35:23 WARNING [main] Exception raised during build(gsa/digitalgov.gov@id:110147):Encountered a bad command exit code!**

Command: 'inv build-hugo --branch=master-1 --owner=gsa --repository=digitalgov.gov --site-prefix=preview/gsa/digitalgov.gov/master-1 --base-url=/preview/gsa/digitalgov.gov/master-1'

Exit code: 255

Stdout: already printed

Stderr: already printed

**Comment by saracope** [comment]
I made a bunch of updates, but it looks like the summary is still not showing:
🔎[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/digitalgov.gov/master-1/event/2020/02/25/making-a-mobilefriendly-website-using-adapt/)

@jeremyzilar would love to pair on this fix

**Comment by saracope** [comment]
Changes I made (mostly by going to the Workflow tool and comparing the formatting):

1. On line 7, the `summary` field contained a quote. I added an escape character `\` before the double-quotes at the beginning and end of it so they would be ignored when the page was processed.
```\"fully functional and usable on common mobile devices.\"```


2. Line 18 had a set of triple dashed lines that tells the system to stop processing the page. I removed these triple dashes. 
The specific error was `"yaml: line 16: found unexpected end of stream"`


3. On line 60, I removed the redirects section as it didn't seem properly formatted (according to what I saw in the Workflow tool events page). I also believe this section is only to be used for fully redirecting an old page/event that was posted. So anything listed here would no longer be displayed themselves; those pages would redirect to this event which didn't seem correct.


4. On line 32, added `event_platform: zoom` and removed the extra wording from the summary about using zoom.


5. Moved the "this talk is hosted by..." section to after the triple dashes

**Comment by saracope** [comment]
I'm not sure why the Federalist build still says Error, but it has completed fine.
Screen Shot 2020-02-14 at 4 03 04 PM
 🔎[Preview](https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/digitalgov.gov/master-1/event/2020/02/25/making-a-mobilefriendly-website-using-adapt/) is available

**Pull request merged**
