### PR TITLE
5/7 Add new post: Two Complementary Teams With the Same Goal

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
**Two Complementary Teams With the Same Goal** 
How the Presidential Innovation Fellows and 18F teams support each other at agencies

Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/18F-PIF-post/2019/05/07/two-complementary-teams-with-same-goal/

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
alt text: A photo of Acting Executive Director of 18F, Angela Colter, addressing the new group of Presidential Innovation Fellows in January 2019.

caption: Angela Colter (standing) and the new cohort of Presidential Innovation Fellows, January 2019.

010919_pif_lightning_talks-2_1024

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar Image #2 

**Caption**: This graphic lists the ways 18F and the PIF offer complimentary solutions that leverage their strengths for agencies. 

**Alt text**: A graphic shows blue and black geometric shapes with text on a white background. A vertical double-headed arrow, colored with a top-down gradient merging blue and black, is on the left. It is to indicate the extent each group is focused on more; Strategy (in blue at the top), versus Execution (in black at the bottom). To the right of the arrow, the PIFs are represented by a blue equilateral triangle pointing downward. The text on it shows that most of their work falls under the Strategy side, focusing on areas such as: Senior Leadership, Product Strategy, Data and Artificial Intelligence Strategy, Strategic Partnerships, Culture Change, and Customer Experience. To the right of the PIF triangle, 18F is represented by a black triangle pointing upward, with white text that shows that most of their work falls under the execution side, focusing on Product roadmaps, User-centered design sprints, Customer journey maps, Product builds, Agile coaching, and Content design and architecture.


18F graphic_v2_Page_1-triangles

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar tiny update on the alt text above

**Comment by jeremyzilar** [comment]
I just added the image @ToniBonittoGSA Let me know if this is OK

**Pull request merged**
