### PR TITLE
New Adobe Connect and Google Meet event_platform options

### PR DESCRIPTION
**Pull request by jeremyzilar**
This change adds in a new Adobe Connect `event_platform` type for event pages.

### To-do 

- [x] copy for this still needs to be reviewed 
- [x] We need a link to download the correct version of Adobe Connect (_for govt peeps_)
- [x] We need a new link for the "test your settings". The one we were given doesn't work.

image

## Google Meet

Screen Shot 2020-04-15 at 4 05 52 PM

---

**Example** https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/new-event-types/event/2020/04/15/accessibility-intersection-between-plain-language-508/

### CODE REVIEW

**Comment by saracope** [comment]
@Gabr1elleKING Please add a new link for "test your connection"

**Comment by Gabr1elleKING** [comment]
Updated Link for the connection test: 
https://helpx.adobe.com/adobe-connect/using/connection-test-connect-meeting.html

**Comment by saracope** [comment]
Download Connect install: https://helpx.adobe.com/adobe-connect/installconfigure/install-application-for-desktop.html

**Comment by saracope** [comment]
@Gabr1elleKING Please send over the list of the events that need the platform type updated and we can edit those all at once. Thanks!

**Comment by saracope** [comment]
Added the google meet screenshot.

**Comment by saracope** [comment]
Wasn't getting Google Meet to show when testing locally. Added a commit to add Google as an event stage in [the last commit](https://github.com/GSA/digitalgov.gov/pull/2338/commits/617b8b34de7d6682b2ce22c3aeb55c31b2c43136). Please review @jeremyzilar

**Comment by jeremyzilar** [comment]
Looks good 🍾

**Pull request merged**
