### PR TITLE
add patch for eslint issue

### PR DESCRIPTION
**Pull request by RileySeaburg**
## Summary

Should solve this issue mentioned here:
in #7485

## Solution

Rather than directly upgrading to ESLint 9.0 we will patch the affected dependency in the package.json override section.
We have a pattern of doing this already as noted in the [already existing overrides section of the package.json](https://github.com/GSA/digitalgov.gov/blob/3380adc2029be8970f5604a1313b79a3b98f2bf8/package.json#L89)

## How To Test

1. NPM install
2. npm run lint:js

### CODE REVIEW

**Comment by RileySeaburg** [comment]
Tested with path, confirmed no major issues:

image

**Comment by RileySeaburg** [comment]
This is just for conversation; we don't need to merge if we find a better solution

**Comment by nick-mon1** [comment]
@RileySeaburg Can confirm that patch removes alerts and works.

```bash
 npm run lint:js
> digitalgov.gov@2.0.0 lint:js
> eslint './themes/digital.gov/src/js/*.js' './config/typescript/**/*.ts'
```


```bash
npm audit
found 0 vulnerabilities
```

**Comment by mejiaj** [comment]
@RileySeaburg, thanks for creating the PR.

I was able to successfully install and verify 0 vulns.

```sh

> digitalgov.gov@2.0.0 prepare
> husky install

husky - Git hooks installed

changed 2 packages, and audited 948 packages in 706ms

186 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I also modified `glossary.js` to see report and saw the expected message:

```sh
digitalgov.gov on  rs-es-lint-fix [$!1] via  v20.11.1 via 💎 v2.7.2
➜ npm run lint:js

> digitalgov.gov@2.0.0 lint:js
> eslint './themes/digital.gov/src/js/*.js' './config/typescript/**/*.ts'


/Users/jmejia-a/web/digitalgov.gov/themes/digital.gov/src/js/glossary.js
   7:3  error  Delete `······`  prettier/prettier
   8:1  error  Delete `······`  prettier/prettier
   9:3  error  Delete `······`  prettier/prettier
  10:3  error  Delete `······`  prettier/prettier
  11:3  error  Delete `······`  prettier/prettier
  12:3  error  Delete `······`  prettier/prettier
  13:3  error  Delete `······`  prettier/prettier
  14:1  error  Delete `······`  prettier/prettier
  15:1  error  Delete `······`  prettier/prettier

✖ 9 problems (9 errors, 0 warnings)
  9 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by RileySeaburg** [comment]
Huh, guess I should merge this then?

**Review by nick-mon1 — APPROVED** [review]

**Pull request merged**
