### PR TITLE
Update Resource “how-to-present-like-a-pro”

### PR DESCRIPTION
**Pull request by Schultea**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by Schultea** [comment]
Getting a 404 on the page: https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/cms/resources/how-to-present-like-a-pro/resources/%3cnil%3e?dg

**Comment by ToniBonittoGSA** [comment]
> Getting a 404 on the page: https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/cms/resources/how-to-present-like-a-pro/resources/%3cnil%3e?dg

there was some weird code.. I removed; hopefully will fix it

**Comment by ToniBonittoGSA** [comment]
@Schultea, what is `source: digitalgov` ? 
It was added to the front matter

**Comment by Schultea** [comment]
> @Schultea, what is `source: digitalgov` ?
> It was added to the front matter

**Comment by Schultea** [comment]
@ToniBonittoGSA I was experimenting adding it to the home page per Sara's comment in https://github.com/GSA/digitalgov.gov/pull/3800. I may have misunderstood what to do. 

> > @Schultea, what is `source: digitalgov` ?
> > It was added to the front matter

**Comment by Schultea** [comment]
@ToniBonittoGSA I was experimenting adding it to the home page per Sara's comment in https://github.com/GSA/digitalgov.gov/pull/3800. I may have misunderstood what to do.

**Comment by ToniBonittoGSA** [comment]
Ahh, got it. closing; will explain in Slack

**Pull request closed without merging**
