### PR TITLE
RPA Community page edits + use cases section

### PR DESCRIPTION
**Pull request by jeremyzilar**
This makes some edits to the RPA community page to reduce the amount of text at the top of the page. In addition, we are adding in a new section on the page that will link off to a form for collecting RPA use cases.

**Doc:** https://docs.google.com/document/d/1S_gvAcPDhkHBBr1senzIpYsOInIR3k3UQjcUDnhFvco/edit?ts=5e5e7c9c

---

**Preview:** https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/rpa-use-case/communities/rpa/

### CODE REVIEW

**Comment by jeremyzilar** [comment]
@saracope 
Nicholas just reached out with the form URL https://feedback.gsa.gov/jfe/form/SV_5AuaO2sJP5Pbi4J and said this is ready to go

**Comment by jeremyzilar** [comment]
I added the form URL

**Comment by saracope** [comment]
Is this supposed to be showing the playbook cover image? I see it in the files but not on the page.

**Comment by jeremyzilar** [comment]
@saracope No. removed it from the page, as it did not fit.

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar 

change a to an for: 
> Submit a RPA Use Case

PDF link needs to give file info: 
> (PDF, 1.6 MB, 70 pages)

**Pull request merged**
