### PR TITLE
added alias for Social Media Analytics hackpad

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
/resources/federal-social-media-analytics-toolkit-hackpad/ 

should redirect to: https://www.digitalgov.gov/2013/04/19/social-media-metrics-for-federal-agencies/

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
Hackpad: https://hackpad.com/ep/pad/static/fZMN6NndIxR

**Comment by ToniBonittoGSA** [comment]
Notes https://github.com/GSA/digitalgov.gov/issues/334

**Comment by ToniBonittoGSA** [comment]
@thisisdano 
a 2nd one ~ 

/resources/federal-social-media-analytics-toolkit-hackpad/

does not redirect to: 

https://www.digitalgov.gov/2013/04/19/social-media-metrics-for-federal-agencies/

**Comment by jeremyzilar** [comment]
Looking at this.

**Pull request merged**
