### PR TITLE
Update 2016-06-20-how-to-make-your-facebook-content-pop-with-images.md

### PR DESCRIPTION
**Pull request by AllanGivens**
If mentioning tools or software prospects should have an idea of what other users think via unbiased reviews and other sources.

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
Hi Allan,

Thanks for the suggestion, but as a federal government website, we cannot link to a site like this -- at the very top is, "When readers buy products and services discussed on our site, we often earn affiliate commissions that support our work. Learn more." 

It would come across as an endorsement of this site/business, which is not permitted. 

Best regards,
 Toni

**Comment by AllanGivens** [comment]
Hi Tony,

Thanks for the email! I see what you mean. I am very sure though this publication does not have a product themselves though. They are an educational publication that happens to make money off of affiliate relationships but their content is education based and non promotional in context. I’ve actually seen them used as a resource and contribute to other government entities (see below). I do appreciate your quick response though in regards to this resource.

Example: https://www.mbda.gov/news/blog/2017/09/bringing-brick-and-mortar-online

Excuse any typing errors sent from my iPhone

**Comment by AllanGivens** [comment]
Sorry,

Toni, just realized I misspelled your name in my last email. My apologies.

Excuse any typing errors sent from my iPhone

**Comment by ToniBonittoGSA** [comment]
No problem on the name; happens all the time.. :) 

That author works for that business website; at the end: "Blogged by Krista Fabregas a staff writer and ecommerce analyst for Fit Small Business, specializing in ecommerce." MBDA may have asked her to write it. 

It's one thing if it's one of many similar links in an article from the start -- like your MBDA example above -- however, adding something like this in almost 2 1/2 years later, as a request from a private citizen, could come across as a plug/endorsement/etc. for Fit Small Business. 

Again, we really appreciate the suggestion (we get lots of similar requests each week via email), but it is not something we are permitted to do at this time. 

Thx so much!
 Toni

**Pull request closed without merging**
