### PR TITLE
Adding Authors and Topics to event page

### PR DESCRIPTION
**Pull request by DanielJPino-ux**
adding authors and topics to event page

This PR implements the following **changes:**

* adding: - alexis-bonnell, dr-kelvin-droegemeier, drew-zachary, ellen-ryan, jarah-meador, jenn-gustetic, jennifer-shieh,  jim-reuter,  john-mclaughlin, ku-mcmahan, lauren-algee, marc-kuchner, sarah lloyd-stevenson, sophia-b-liu, and taylor-gilliland to event page as speakers/ authors
* adding topics to page: challenges and prizes, citizen science, and innovation

**URL / Link to page**
https://digital.gov/event/2019/06/14/us-government-open-innovation-summit-transformation-through-citizen-science-prize-competitions/

### CODE REVIEW

**Comment by DanielJPino-ux** [comment]
@saracope  - this federalist preview is coming up as a 404 page - any chance you can review when you get a moment?

**Comment by ToniBonittoGSA** [comment]
https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/Author-and-Topics-Page-Update/event/2019/06/us-government-open-innovation-summit

**Comment by saracope** [comment]
Hmmm the topics and authors don't seem to be showing in the preview I see

**Comment by ToniBonittoGSA** [comment]
https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/Author-and-Topics-Page-Update/event/2019/06/14/us-government-open-innovation-summit-transformation-through-citizen-science-prize-competitions/

**Pull request merged**
