### PR TITLE
Cleaning up Resource pages - Multilingual/LEP

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
Main Resources pg
Main Style Guides & Glossaries pg
Style Guides & Glossaries sub-pages (5)

### CODE REVIEW

**Comment by jeremyzilar** [comment]
Here is a preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/Dec13-cleanup/

**Comment by jeremyzilar** [comment]
Here is the page that shows the anchor link script and how it works.
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/how-fedramp-supports-agencies-a-resource-overview/resources/contact-center-guidelines/getting-started-with-your-contact-center/#planning
It will scroll the user to the point on the page where the anchor link is.
Let me know if that is too slow.

**Comment by ToniBonittoGSA** [comment]
The Header line is still blocked by the menu
screen shot 2017-12-13 at 9 14 24 pm

**Comment by ToniBonittoGSA** [comment]
Notes for new build: 

**Spanish Language Style Guide and Glossaries** (main page)
https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/
 - shortened summary
 - simplified wording in bulleted list
 - linked GSA/ANLE Agreement PDF

Breadcrumb should be: 
[Resources](https://www.digitalgov.gov/resources/)

---
**Spanish Health Care Terms in the United States** (sub-page)
https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/spanish-health-care-terms-in-the-united-states/
 - Added summary
 - converted from table to list; applied formatting
 - intro line
*Google keeps auto translating to English.. is there any way to prevent?

Breadcrumb should be: 
[Resources](https://www.digitalgov.gov/resources/) / [Spanish Language Style Guide and Glossaries](https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/)

---
**Grammar** (sub-page)
https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/spanish-language-style-guide-and-glossaries-grammar/
 - Fixed top bullet list for anchor menu
 - Fixed HTML entities and numbers
 - added summary
 - kept 4 small/narrow tables
 - linked GSA/ANLE Agreement PDF

Breadcrumb should be: 
[Resources](https://www.digitalgov.gov/resources/) / [Spanish Language Style Guide and Glossaries](https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/)

---
**Frequently Mistranslated English Terms** (sub-page)
https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/spanish-language-style-guide-glossaries-frequently-mistranslated-english-terms/
 - converted from table to list; applied formatting
 - summary
 - intro line

Breadcrumb should be: 
[Resources](https://www.digitalgov.gov/resources/) / [Spanish Language Style Guide and Glossaries](https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/)

---
**Information Technology Terms** (sub-page)
https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/spanish-language-style-guide-glossaries-information-technology-terms/
 - converted from table to list; applied formatting
 - summary
 - intro line

Breadcrumb should be: 
[Resources](https://www.digitalgov.gov/resources/) / [Spanish Language Style Guide and Glossaries](https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/)

---
**Internet Resources** (sub-page)
https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/spanish-language-style-guide-glossaries-internet-resources/
 - summary
 - intro line
* Should we add to this page, Official Directory of Federal Agency Names in Spanish https://gobierno.usa.gov/agencias-federales/ ?

Breadcrumb should be: 
[Resources](https://www.digitalgov.gov/resources/) / [Spanish Language Style Guide and Glossaries](https://www.digitalgov.gov/resources/spanish-language-style-guide-and-glossaries/)

---
We also need to redirect old "Top 10" post https://www.digitalgov.gov/2012/08/12/top-10-best-practices-for-multilingual-websites/ 
to new "Top 10" Resource page https://www.digitalgov.gov/resources/top-10-best-practices-for-multilingual-websites/.

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA — check this preview for the anchor link preview:
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/Dec13-cleanup/resources/contact-center-guidelines/getting-started-with-your-contact-center/

**Comment by ToniBonittoGSA** [comment]
Awaiting one more edit from Laura

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar this is ready if you can push/approve today

**Pull request merged**
