### PR TITLE
Update "Connect with us" box on community landing pages

### PR DESCRIPTION
**Pull request by nick-mon1**
## Summary
Update the "Connect with us" box with community logo, brand colors and survey link to replace old email signup process.

## Preview

[Link to Preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/nl-update-communities-page/communities/)

<details><summary>Before/After</summary>
<p>

Before
Screenshot 2024-08-27 at 1 44 18 PM

After
Screenshot 2024-08-29 at 9 34 30 AM

</p>
</details> 

## Solution

Updates the "Connect with us" box to reflect community brand colors and updated copy for the new join button link to the Qualtrics survey signup.

- [x] updated layout for communities page
- [x] updated color for web analytics community
- [x] add survey link

## How To Test

1. Visit any communities page
2. Confirm layout and copy changes 
3. "Join" button links to Qualtrics survey

### CODE REVIEW

**Review by makaylahipke — COMMENTED** [review]
Capitalize to "Contact Center Community" in $community_acronym and $community_join_copy

**Review by makaylahipke — APPROVED** [review]

**Review by RileySeaburg — APPROVED** [review]
Great work, looks awesome!

**Comment by RileySeaburg** [comment]
This has a buld error, checking

**Review by RileySeaburg — COMMENTED** [review]
```
Provided file to checksum does not exist.

2024-09-03 13:59:59 INFO [setup-node] ! WARNING: Version 'v20.11.1' does not exist.

```

https://pages.cloud.gov/sites/193/builds/389970/logs

**Pull request merged**
