### PR TITLE
Add State of Federal RPA Report page to RPA Guide

### PR DESCRIPTION
**Pull request by saracope**
This PR implements the following **changes:**

* adds a new page to the RPA guide for the State of Federal RPA report

https://digital.gov/guides/rpa/

### CODE REVIEW

**Review by mitchell-lucia — DISMISSED** [review]

**Review by mitchell-lucia — APPROVED** [review]

**Comment by mitchell-lucia** [comment]
Didn't mean to make certain changes, eventually figured out how to revert them. Reverted all except removing the image that didn't scale well out of the state-of-federal-rpa.md, will create a separate issue later if the RPA team decides on a new graphic.

**Comment by mitchell-lucia** [comment]
Didn't mean to make certain changes, eventually figured out how to revert them. Reverted all except removing the image that didn't scale well out of the state-of-federal-rpa.md, will create a separate issue later if the RPA team decides on a new graphic.

**Review by mitchell-lucia — DISMISSED** [review]

**Comment by saracope** [comment]
What's the status of this? @ToniBonittoGSA @mitchell-lucia

**Comment by mitchell-lucia** [comment]
Submitted PR #3430 so the pdf will be 508 compliant, otherwise we should be good to post it

**Pull request merged**
