### PR TITLE
Updating address in event and fixing bug in address display for all events

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
### Fixes

- Typo in address on the [Workshop: Making Government Websites with GitHub, Federalist & U.S. Web Design Standards](https://www.digitalgov.gov/event/workshop-making-government-websites-with-github-federalist-us-web-design-standards/) event page
- Light copy edit/grammar fixes
- Updated location/venue name & address in [the event generator](https://www.digitalgov.gov/new-event/)

Issue: https://github.com/GSA/digitalgov.gov/issues/203

### CODE REVIEW

**Comment by jeremyzilar** [comment]
Are you sure it should be *U.S. General Services Administration* and not *The U.S. General Services Administration*?

**Comment by ToniBonittoGSA** [comment]
Yes; no "the" used on GSA.gov (see footer)

**Comment by jeremyzilar** [comment]
Here are the changes @ToniBonittoGSA : https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/ToniBonittoGSA-patch-2/

**Comment by jeremyzilar** [comment]
This looks good 👍

**Pull request merged**
