### PR TITLE
Redirect Terms of Service pages

### PR DESCRIPTION
**Pull request by jeremyzilar**
This change redirects the individual Terms of Service pages to the main terms of service page, then deletes the files for the individual pages. — (https://github.com/GSA/digitalgov.gov/issues/231)

### Main Page
https://www.digitalgov.gov/resources/negotiated-terms-of-service-agreements/

### Pages that will be redirected
1. https://digitalgov.gov/resources/chatwing-federal-terms-of-service
1. https://digitalgov.gov/resources/classmarker-federal-terms-of-service
1. https://digitalgov.gov/resources/eventbrite-federal-terms-of-service
1. https://digitalgov.gov/resources/github-federal-terms-of-service
1. https://digitalgov.gov/resources/govloop-federal-terms-of-service
1. https://www.digitalgov.gov/resources/hackpad-federal-terms-of-service
1. https://www.digitalgov.gov/resources/ideascale-federal-terms-of-service
1. https://www.digitalgov.gov/resources/instagram-federal-terms-of-service
1. https://www.digitalgov.gov/resources/mandrill-federal-terms-of-service
1. https://www.digitalgov.gov/resources/measured-voice-federal-terms-of-service
1. https://www.digitalgov.gov/resources/my-commetrics-federal-terms-of-service
1. https://www.digitalgov.gov/resources/news-genius-federal-terms-of-service
1. https://www.digitalgov.gov/resources/pinterest-federal-terms-of-service
1. https://www.digitalgov.gov/resources/quora-federal-terms-of-service
1. https://www.digitalgov.gov/resources/slideshare-federal-terms-of-service
1. https://www.digitalgov.gov/resources/socialoomph-federal-terms-of-service
1. https://www.digitalgov.gov/resources/stack-exchange-federal-terms-of-service
1. https://www.digitalgov.gov/resources/storify-federal-terms-of-service
1. https://www.digitalgov.gov/resources/surveymonkey-federal-terms-of-service
1. https://www.digitalgov.gov/resources/thunderclap-federal-terms-of-service
1. https://www.digitalgov.gov/resources/tint-federal-terms-of-service
1. https://www.digitalgov.gov/resources/trello-federal-terms-of-service
1. https://www.digitalgov.gov/resources/twitter-federal-terms-of-service
1. https://www.digitalgov.gov/resources/uservoice-federal-terms-of-service
1. https://www.digitalgov.gov/resources/vine-federal-terms-of-service

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar 1 thru 5 are missing the www. (all the rest are fine) ~ will that cause a problem?

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA They will be fine too. They should all redirect to the main TOS page, with or without the `www`.

**Comment by thisisdano** [comment]
So, this change collects all our TOS information on a single page (`resources/negotiated-terms-of-service-agreements/`) and redirects all previous individual TOS pages to that master collection page?

**Comment by jeremyzilar** [comment]
Correct @thisisdano — Here is the issue https://github.com/GSA/digitalgov.gov/issues/231

**Comment by jeremyzilar** [comment]
@thisisdano There are so many problems with thes page. I am not even diving in to the content or clarity of the wording. This is just to focus on redirecting and deleting some of the pages and fixing links to files in the main page.

I will fix those broken links you mentioned.

**Pull request merged**
