### PR TITLE
Add new event: Legal Obligations

### PR DESCRIPTION
**Pull request by jthalls**
New event needs review on event description. @jeremyzilar or @ToniBonittoGSA

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
Hey Janelle,

there's a broken featured image for that on https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/event-lep-legal-obligations/events/

**Comment by ToniBonittoGSA** [comment]
Image is also broken on LEP event page https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/event-lep-legal-obligations/event/limited-english-proficient-audiences-legal-obligations-practical-solutions/  

It looks like the formatting (bold, header, list) isn't displaying correctly

**Comment by jthalls** [comment]
@ToniBonittoGSA let me try fixing

**Comment by ToniBonittoGSA** [comment]
the DOJ featured image isn't in the Images list, but I found it in an old newsletter  https://cdn2.hubspot.net/hub/1962994/hubfs/DigitalGov_Featured_Images/featured-301-x-212-US-DOJ-Dept-of-Justice-facebook.jpg

**Pull request merged**
