### PR TITLE
Added logic to set href for service link

### PR DESCRIPTION
**Pull request by nick-mon1**
## Summary

Visiting https://digital.gov/services/ and clicking each link will take back to the top of the page.
It should link to the external or internal service.

### Preview
[Link to Preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/nl-fix-link-for-services/services/)

### Solution

Added logic to properly set the link for each `card-service`.

```go
  {{- $href := "" -}}

  {{ if .Params.source_url }}
    {{ $href = .Params.source_url }}
  {{ else }}
    {{ $href = .Params.url }}
  {{ end }}
```

### How To Test

All links point to an external page except **U.S. Digital Registry** and the **DAP** guide.

---

### Dev Checklist

- [x] PR has correct labels
- [x] A11y testing (voice over testing, meets WCAG, run axe tools)
- [x] Code is formatted properly

### CODE REVIEW

**Review by clmedders — APPROVED** [review]
LGTM - all links are leading to the excited external site and are not sending me to the top of the page

**Review by sarah-sch — DISMISSED** [review]
The U.S. Digital Registry link isn't working--is that because it's an internal link and gets messed up in the federalist preview? Otherwise looks good--the bug that was reported has been fixed.

**Review by mejiaj — COMMENTED** [review]
@nick-mon1 if one case is more common than others, would it make more sense to set that as the default?

**Pseudocode example**

```
// Save the fallback.
{{ $fallback_url := .Params.source_url }}

// Set the override with fallback.
{{ .Params.url | default $fallback_url }}
```

**Comment by nick-mon1** [comment]
Thanks for the comments team!

- @sarah-sch The link is now fixed for federalist.
- @mejiaj I've simplified the logic with your suggestion.

**Review by sarah-sch — APPROVED** [review]
Looks good!

**Review by bonnieAcameron — APPROVED** [review]

**Review by clmedders — APPROVED** [review]

**Review by mejiaj — APPROVED** [review]
Looks good, tested all links in services pages.

**Review by ToniBonittoGSA — APPROVED** [review]
w00t!

**Pull request merged**
