### PR TITLE
RPA CoP Lead Update

### PR DESCRIPTION
**Pull request by mitchell-lucia**
This PR implements the following **changes:**

* created author page for James Gregory
* added management committee to "Who We Are"
* re-ordered headings to align with Jan 2021 template changes

**URL / Link to page**

<https://digital.gov/communities/rpa/>

### CODE REVIEW

**Comment by saracope** [comment]
@Schultea Can you review this update plz/thx!

**Review by Schultea — COMMENTED** [review]
Looks great! This is good to go!

**Comment by Schultea** [comment]
> @Schultea Can you review this update plz/thx!

You got it.

**Review by saracope — DISMISSED** [review]

**Comment by mitchell-lucia** [comment]
Re-requesting review due to conflict that had to be resolved

**Review by saracope — APPROVED** [review]

**Pull request merged**
