### PR TITLE
Changed 3 'DigitalGov Search' to 'Search.gov'

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
DigitalGov Search is now search.gov and we need to make the name change around digitalgov.gov to reflect the new name:

**Preview:**
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/ToniBonittoGSA-patch-4/services/ 

### What we made better
- Changing label in the services navigation to search.gov
- Updated the `services/search` page title to reflect Search.gov
- Updated the service page to reflect Search.gov

### CODE REVIEW

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA — can you add links to the Preview URLs to the edit notes on what changed above?

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar updated

**Comment by jeremyzilar** [comment]
I am going to update all the pages affected in this issue https://github.com/GSA/digitalgov.gov/issues/240

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA Here is what I updated:

- Changed label in the services navigation to search.gov
- Updated the services/search page title to reflect Search.gov
- Updated the service page to reflect Search.gov

I also looked into changing all 129 instances of ` DigitalGov Search ` to ` Search.gov ` but wanted to ask you first, if you thought this was a good idea to do. 

In general, I am OK with making changes to content in the site to reflect new changes. I just want to make sure we don't  break anything in the process

**Comment by ToniBonittoGSA** [comment]
Not sure about an across the board change -- in Pages (Resources, Services, Communities, etc.), yes -- but not past article posts. 

Also, would probably be best for SEO to have **Search.gov (formerly DigitalGov Search)** 
 - but, would have to be careful.. if text is on a hyperlink, the part in parentheses would not need to be linked.

Were you able to generate a list of which pages (like the Resources) that have it?

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA this is the only page in the Resources + Services where `DigitalGov Search` appears. I replaced it out: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/ToniBonittoGSA-patch-4/resources/mobile-user-experience-guidelines-and-recommendations/

**Comment by ToniBonittoGSA** [comment]
Awesome -- on that same line, there's a typo; **howto** should be **how-to**

> Guidelines to making Mobile Websites mobile search friendly – A howto guide written by the Search.gov (formerly DigitalGov Search) team

**Comment by jeremyzilar** [comment]
Fixed. You should see that change once it builds: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/ToniBonittoGSA-patch-4/resources/mobile-user-experience-guidelines-and-recommendations/

**Comment by ToniBonittoGSA** [comment]
thank you! good to go

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA You will have to ✅ this

**Pull request merged**
