### PR TITLE
Update 2020-02-11-federal-crowdsourcing-webinar-series-episode-7.md

### PR DESCRIPTION
**Pull request by ayerkes**
Adding authors and topics

**Preview:**: https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/digitalgov.gov/Adding-topics-and-presenters/event/2020/02/11/federal-crowdsourcing-webinar-series-episode-7/

### CODE REVIEW

**Comment by twgsa16** [comment]
@ayerkes - I don't think this should be live just yet. Still waiting for Amin's approval of content in the Google doc. Can you help?

**Comment by saracope** [comment]
@twgsa16 I can revert the latest commit to remove the page. Give me a minute.

**Comment by twgsa16** [comment]
THANK YOU @saracope!

**Comment by saracope** [comment]
I removed it. Start a convo with me when you're ready to add it back. @twgsa16

**Comment by twgsa16** [comment]
Deal. Thanks, @saracope!

**Comment by twgsa16** [comment]
@saracope - Sara, I have a couple of edits from the Amin, which I need to make, and then we can bring this back to life. Can you help?

**Pull request merged**
