### PR TITLE
img tests new blogs

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
img tests new blogs

## Summary

Basic description of work done.

## Preview

right align glitch in both:

https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/img-tests-new-blogs/2024/10/07/building-a-culture-of-customer-experience-across-government/ 

https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/img-tests-new-blogs/2024/10/11/making-targeted-improvements-to-nps-gov-a-case-study-from-the-national-park-service/ 

## Solution

Provide a summary of the solution this PR offers.

## How To Test

1. First Step
2. Second Step
3. Third Step

### CODE REVIEW

**Comment by nick-mon1** [comment]
@ToniBonittoGSA Is this just a test or should we merge this?

**Comment by RileySeaburg** [comment]
We have merge conflicts now @nick-mon1

**Comment by nick-mon1** [comment]
@RileySeaburg Fixed!

**Comment by ToniBonittoGSA** [comment]
Thx @nick-mon1 @RileySeaburg

**Pull request merged**
