### PR TITLE
Improvements to the Required Web Content and Links page

### PR DESCRIPTION
**Pull request by jeremyzilar**
Based off of a conversation with members of the Federal Web Council, we are making a number of improvements to our [_**"Required Web Content and Links"**_](https://digital.gov/resources/required-web-content-and-links/) page.

## What we heard

- When teams are asked to comply with policy, they often need to see the specific wording of the law/policy in addition to the recommended best practice. 
- Having a link to the correct policies is helpful, but calling out the specific text would help more people to see what the actual wording is
- Work to incorporate the USWDS into this guidance
- we are missing **OMB M-17-06** as the requiring policy on many of the links

## What we made better

- [x] Introduced a way to contextually embed and highlight relevant policies directly on the page ✨ 
- [x] Added **OMB M-17-06** as the "required by" policy on a number of the required links
- [x] Clarified the "About Page" requirement to indicate that many of the links we previously listed, can live on the agency about page
- [x] Reorganized the headings to reflect the purpose, more that the specific name of the link
- [x] Added copy to describe USA.gov in the "Government Customer Support" section
- [x] Expanded on the text at the top of the page
- [x] Added a link to the USWDS footer component _(will do more in this direction in the coming weeks)_

---

**Current page:** https://digital.gov/resources/required-web-content-and-links/

**PREVIEW of changes:** https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/digitalgov.gov/law-notice/resources/required-web-content-and-links/

### CODE REVIEW

**Comment by dawnpm** [comment]
@jeremyzilar overall I think this is great! A couple of suggestions
* add a link to the policy memo in "As M-17-06 says"
* spelling error in "For specific implementaiton guidance" (recognizing the copy isn't final yet!)
* Is there more info available on what "Translating privacy policies into a standardized machine-readable format." means?
* make the `*` note mark a link to wherever that footnote is
* in the `Required on:` sections, might be nice somehow to highlight the ones that are unique to that item, so people don't gloss over after seeing the common ones.
* I like the embedded policy text, but not sure if it helps to have it reiterated every section. It doesn't seem to hurt, though. Then at the bottom I see there are other laws in play, too, so maybe I retract this comment, but it still feels mostly relevant. Maybe offer as an expanding section to click open, rather than a scrolling box?
* Under Budget and Performance, whose which websites' homepages does this need to be on? Just says `Homepage`. Same for No FEAR Act. All websites? For program level websites, would these link to the parent agency's pages for these items?

**Comment by jeremyzilar** [comment]
Thanks @dawnpm 🎉 

Of what you suggested, here is what I have fixed:

- [ ] removed the `*` from the text and from the footnote. I made that more clear in the text at the top. Felt redundant to emphasize it as an asterisk 
- [ ] fixed spelling error in "For specific implementaiton guidance"

I am looking at the others :)

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar for 
> These requirements apply to executive departments and agencies and their public websites. Check the specific law to see if it also applies to the judicial or legislative agencies, or to intranets.

 - _executive_ should be Executive Branch
  -- link to: https://www.usa.gov/executive-departments

**Comment by jeremyzilar** [comment]
I am not sure we need the **Cross-agency portals** section. It is only referenced as an aside in [M-05-04](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2005/m05-04.pdf):

>  _8) other cross government portals or links required by law or policy._

**Comment by jeremyzilar** [comment]
@dawnpm I like your idea of making the embedded policy text expand to click open, rather than a scrolling box. That might be easier for people to use.

Do others have thoughts?

**Comment by ToniBonittoGSA** [comment]
See tabbing issue https://github.com/GSA/digitalgov.gov/issues/1259

**Comment by ToniBonittoGSA** [comment]
Love the document icons -- but we should remove the links on them since they are linked as text immediately after.

**Comment by jeremyzilar** [comment]
## What was changed
- [ ] the policy embeds now use the [USWDS accordion component](https://designsystem.digital.gov/components/accordion/)
- [ ] removed all references to OMB M-05-04
- [ ] Removed the "Cross-agency portals" section, as it was just an aside mentioned in `OMB M-05-04` with no clear guidance or direction
- [ ] Changed the "No Fear Act Data" heading to "Equal Employment"
- [ ] Clarified the copy at the top of the page

**Comment by afeijoo** [comment]
@jeremyzilar 

A couple of suggestions:

* Simplify the opening paragraph from `... on “your agency’s principal website and on any known sub-agency or other major entry points” to your agency site.` to `... on your site.`
* Update the fourth bullet from `which law requires those links` to `which law or policy requires those links` 
* Update `In addition to being compliant with the law, it is recommended that agencies implement these user-friendly required links with in clear, user-friendly way.` to `Use the guidance below to implement these required links with in clear, user-friendly way.`
* Remove `It is a public domain website. You may link to USA.gov at no cost.`

**Comment by jeremyzilar** [comment]
Solid recommendations @afeijoo, I just made those edits 👍

**Comment by jeremyzilar** [comment]
A things to note that we changed in addition to the comments above:

- We removed the small graph + link to the USWDS footer because it might confuse people who arrive at the link to find that the USWDS footer does not incorporate the required links.
- we added an embed to OMB M-03-22 in the **Privacy Policy** section

**Comment by jeremyzilar** [comment]
OK, we are ready to merge in these changes. Thank you @dawnpm @ToniBonittoGSA @afeijoo and the many people who submitted comments over email 🎉

**Pull request merged**
