### PR TITLE
[WIP] Accessibility changes from audit

### PR DESCRIPTION
**Pull request by thisisdano**
Made the changes outlined here
https://github.com/GSA/digitalgov.gov/issues/434

### todo
- [x] Fix `go to top` button
- [x] Assure all links have a `:focus` state
- [ ] "The visual focus does not remain within a modal dialog box until closed" — find out what this refers to and address
- [x] Add label to search field
- [x] `Read more` links need aria label or title attributes
- [x] Add `alt` attribute to GSA logo
- [x] See below
> News image links have alt description different from the actual link. This results in a confusing experience for a screen reader user. ex. "A video call with 4 users..." is not what the image is there for
- [x] "Alt tags for DAP and Challenge.gov images does not contain the text in the images" — I don't think this is really important as the text in these images is not important, but make sure
- [x] Address the following contrast issues
  - [x] White "Search" text on button
  - [x] Red hover text on green in menu
  - [x] Read more text on button
  - [x] Red "#ff5049" text on white - Events section
  - [x] Pink text in footer
- [x] Address following header issues:
  - [x] Articles in each section have the same heading level as the section they are in. Example: h3 - Latest news h3 - A better digital gov
  - [x] "Latest News" should be h2, "A better digital gov" should be h3
  - [x] Should `DigitalGov` be an `h1`?
- [x] Fix `skip nav` functionality
- [x] Assure all `id`s are unique

Most of the obvious changes are color changes to conform to Section 508 / WCAG 2.0 color contrast guidance.

- - -

**New footer background for color contrast**
screen shot 2018-02-20 at 10 07 26 am

- - -

**New default link color for color contrast**
screen shot 2018-02-20 at 10 07 17 am

- - -

**New, consistent focus treatment**
screen shot 2018-02-20 at 10 07 08 am

- - -

**New `Read More` link color for contrast**
screen shot 2018-02-20 at 10 06 57 am

- - -

**New search button for text contrast issues**
screen shot 2018-02-20 at 10 06 38 am

- - -

**New nav highlight text contrast issues**
screen shot 2018-02-20 at 10 06 31 am

- - -

### CODE REVIEW

**Comment by jeremyzilar** [comment]
Looks good @thisisdano. Maybe we should also push https://github.com/GSA/digitalgov.gov/pull/450 to DEMO to as well, to make sure there are not conflicts.

**Comment by jeremyzilar** [comment]
@thisisdano @dano Seems there are conflicts. I can look at those.

**Comment by thisisdano** [comment]
Gotta fix the buttons in this new events section

screen shot 2018-02-21 at 3 54 06 pm

**Comment by thisisdano** [comment]
Hm. I thought I fixed these merge conflicts. I don't see them locally, yet here is says they exist...

**Comment by thisisdano** [comment]
Oh nm. They just mysteriously vanished

**Comment by thisisdano** [comment]
Buttons fixed.

screen shot 2018-02-21 at 4 28 31 pm

**Pull request merged**
