### PR TITLE
Create Resource “an-introduction-to-plain-language”

### PR DESCRIPTION
**Pull request by bonnieAcameron**
Automatically generated by Netlify CMS

Preview: https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.sites.pages.cloud.gov/preview/gsa/digitalgov.gov/cms/resources/an-introduction-to-plain-language/resources/an-introduction-to-plain-language/

### CODE REVIEW

**Comment by bonnieAcameron** [comment]
@nick-mon1 or @mejiaj , can you help me find out what I'm doing wrong with my policy card? it's including everything beneath it.

**Review by nick-mon1 — APPROVED** [review]

**Comment by bonnieAcameron** [comment]
Thanks for the approval! I want to make a couple more indentation edits in markdown before we merge. I'll re-request review shortly!

**Comment by nick-mon1** [comment]
Hey @bonnieAcameron, I've updated several markdown formatting errors that fall mostly on tiny spacing issues. Markdown can be unforgiving when there is a lot of nesting and sub-lists. Let me know if you have any questions.

**Comment by bonnieAcameron** [comment]
> Hey @bonnieAcameron, I've updated several markdown formatting errors that fall mostly on tiny spacing issues. Markdown can be unforgiving when there is a lot of nesting and sub-lists. Let me know if you have any questions.

Looks good, @nick-mon1 ! Thanks for those adjustments.  Can you merge for me?

**Review by nick-mon1 — APPROVED** [review]

**Pull request merged**
