### PR TITLE
4/2 cross post: for 4/3 Partnership Toolkit event

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
Featured image and in-copy image attached below.

Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/ToniBonittoGSA-patch-1/2018/04/02/marketing-government-through-agency-partnerships/

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
**Featured image**:

alt text: USAGov logo
caption: N/A

usagov-logo-new-2017

---

**Post image**:

alt text: A screenshot of the homepage for USAGov's digital toolkit. It has the words, "Ready to Work with You" with two buttons below it; one that says, Get Started, and another that says, View Branding Toolkit.
caption: N/A

usagov marketing the government through agency partnerships

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA There should be a video for this. Can we embed the video as well?

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar I was going to suggest we embed the video https://www.youtube.com/watch?v=mg1W8l1bfqI after it airs; there's already a link to the event page (which has the player) at the end.

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar 

promo vid to embed https://www.youtube.com/watch?v=PS3GS0QrBAI

**Pull request merged**
