### PR TITLE
Update challenges-prizes.md

### PR DESCRIPTION
**Pull request by jennstein2017**
This PR implements the following **changes:**

* Updates to descriptive text in "Who We Are" and "What We Do" sections
* Update number of members in Listserv Join box

**URL / Link to page**

https://digital.gov/communities/challenges-prizes/

### CODE REVIEW

**Comment by ToniBonittoGSA** [comment]
Hi @jennstein2017 do you have the exact number for the members code up in the front matter at the top of the file?

**Comment by jennstein2017** [comment]
Hi Toni -

Our exact number as of today is 800. Though with new adds and auto-deletes
its fluctuating between the 799 - 805 for the past few weeks.

Given the fluctuations and our continued efforts to grow the community, I
was hoping to not put an exact number - one less thing to have to remember
to update.  If an exact number is needed, can we just take this off?  We
already have a reference to 800+ in the "about us" text.

*Jenn Stein, *Open Innovation Program
Contractor - Kaptivate
Technology Transformation Services
U.S. General Services Administration

phone: 888.527.8488 x711 | email: ***@***.***
***@***.***>


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ToniBonittoGSA** [comment]
That's fine; we update the numbers on all Communities a few times a year.

**Comment by ToniBonittoGSA** [comment]
Completed in: https://github.com/GSA/digitalgov.gov/pull/4034

**Pull request closed without merging**
