### PR TITLE
Remove reference to deprecated memo

### PR DESCRIPTION
**Pull request by lachellel**
Removal of Requirements for Accepting Externally Issued Identity Credentials reference
This document was deprecated / rescinded by OMB Memorandum 19-17

A one-line description of the changes you're making and how they'll affect users.

---

**Preview:**

### CODE REVIEW

**Comment by jeremyzilar** [comment]
Thanks @lachellel 🎉

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA Here are the other pages that reference this:
- https://digital.gov/resources/requirements-for-accepting-externally-issued-identity-credentials/
- https://digital.gov/overview-of-the-privacy-act-of-1974-2015-edition/
- https://digital.gov/resources/omb-memos-circulars-executive-orders-and-other-policies/
- https://digital.gov/resources/guidance-for-implementing-the-privacy-provisions-of-the-e-government-act-of-2002-m-03-22/
- https://digital.gov/resources/childrens-online-privacy-protection-rule-coppa/
- https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/
- https://digital.gov/resources/appendix-i-to-omb-circular-no-a-130-federal-agency-responsibilities-for-maintaining-records-about-individuals/

Do we usually just remove these? Or are there places where we keep the reference to the old policy? Each page might be a case-by-case call.

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar 

Hmm.. 

1) https://digital.gov/resources/requirements-for-accepting-externally-issued-identity-credentials/ should redirect to a new page for `OMB Memorandum 19-17`. 

2) Any pages that mention and link to the `Requirements for Accepting Externally Issued Identity Credentials` PDF [like the 2nd bullet on [https://digital.gov/overview-of-the-privacy-act-of-1974-2015-edition/](https://digital.gov/overview-of-the-privacy-act-of-1974-2015-edition/)] can just be changed to link to OMB's new PDF: 

[M-19-17, Enabling Mission Delivery through Improved Identity, Credential, and Access Management](https://www.whitehouse.gov/wp-content/uploads/2019/05/M-19-17.pdf) (PDF, 1 MB, 13 pages, May 2019)

**Comment by saracope** [comment]
Toni will look for an email from RF with the info on what to replace it with.

**Comment by afeijoo** [comment]
cc @RachelF

**Comment by RachelF** [comment]
M-19-17 rescinds the following:
1. M-04-04, E-Authentication Guidance for Federal Agencies
2. M-05-05, Electronic Signatures: How to Mitigate the Risk of Commercial Managed
Services
3. M-06-18, Acquisition of Products and Services for Implementation of HSPD-12
4. M-11-11, Continued Implementation of Homeland Security Presidential Directive
(HSPD) 12 - Policy for a Common Identification Standard for Federal Employees and
Contractors
5. OMB Memorandum, Requirements/or Accepting Externally-Issued Identity Credentials,
October 6, 2011 
So any place on digital.gov that links to any of these old memos should have the link updated to point to [M-19-17, Enabling Mission Delivery through Improved Identity, Credential, and Access Management](https://www.whitehouse.gov/wp-content/uploads/2019/05/M-19-17.pdf) (PDF, 1 MB, 13 pages, May 2019)
Also update any accompanying descriptive text, as needed.
@ToniBonittoGSA @saracope @afeijoo

**Comment by ToniBonittoGSA** [comment]
thanks, Rachel

**Comment by ToniBonittoGSA** [comment]
Will complete when I get back, week of 5/4

**Pull request merged**
