### PR TITLE
New authors: Jonathan Withington

### PR DESCRIPTION
**Pull request by DanielJPino-ux**
creating new author

A one-line description of the changes you're making and how they'll affect users.

---

**Preview:**

### CODE REVIEW

**Comment by saracope** [comment]
This one isn't showing on the preview for me at all:
https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/adding-new-author/authors/jonathan-withington/

Screen Shot 2020-04-22 at 8 54 41 AM


Tried to pull down locally and I think there's a branch name conflict that needs resolved.

**Comment by DanielJPino-ux** [comment]
hi @saracope and @ToniBonittoGSA - any reason this isn't getting blocked?

**Comment by saracope** [comment]
His profile isn't showing. This needs debugged.
https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/adding-new-author/authors/jonathan-withington/

**Comment by saracope** [comment]
Duplicate PR, closing out.

**Pull request closed without merging**
