### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sarah-sch**
Adding icon and logo for AI.gov, which we need for the "Cloud and infrastructure" topic page

## Summary

I am adding to https://github.com/GSA/digitalgov.gov/tree/main/static/logos the icon and logo for AI.gov.

### How To Test

1. Navigate to https://github.com/GSA/digitalgov.gov/tree/main/static/logos
2. Make sure that icon (50 px x 50px) and logo (250 px x 250 px) for AI.gov have been uploaded and are available for use

---

### Dev Checklist

- [ ] PR has correct labels
- [ ] A11y testing (voice over testing, meets WCAG, run axe tools)
- [ ] Code is formatted properly

### CODE REVIEW

**Review by nick-mon1 — CHANGES_REQUESTED** [review]
@sarah-sch I made some minor tweaks to the image name, they can't contain blank spaces and replaced with a hyphen to properly display.

Also, do we need a `source_aigov.md` file or is that going into another PR?
We'll need this to tell the code to look for the new images.

**Comment by sarah-sch** [comment]
> @sarah-sch I made some minor tweaks to the image name, they can't contain blank spaces and replaced with a hyphen to properly display.
> 
> Also, do we need a `source_aigov.md` file or is that going into another PR? We'll need this to tell the code to look for the new images.

Thanks, @nick-mon1! The markdown file will be another PR.

**Review by nick-mon1 — DISMISSED** [review]

**Review by bonnieAcameron — DISMISSED** [review]

**Comment by ToniBonittoGSA** [comment]
Hold until filenames renamed

**Review by nick-mon1 — APPROVED** [review]
LGTM! Thanks @sarah-sch

**Comment by sarah-sch** [comment]
@ToniBonittoGSA - adding you as a reviewer again now that the file name is updated. Thank you!

**Pull request merged**
