### PR TITLE
Create Event “2021/12/2021-12-21-overcoming-your-fear-of-data”

### PR DESCRIPTION
**Pull request by Gabr1elleKING**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by Gabr1elleKING** [comment]
@thisisdano would you mind taking a look at this PR? It looks like it passed but only 2 checks instead of the normal 6, and the link to federalist is giving me a 404.

**Comment by Gabr1elleKING** [comment]
@Schultea this is for the Web analytics / UX event with the Library of Medicine folks. Once this PR gets merged to main would you mind sending the page link to @tdlowden and Jean and Beth M. letting them know the page is live?

**Comment by thisisdano** [comment]
I think this is still running the same number of tests, just perhaps Circle is reporting them differently or GH is displaying them differently. When you see the Circle process `build_test_process`, that includes four subtasks in that workflow:

- `build`
- `html-proofer`
- `test`
- `process`

You can see these in the `Checks` tab here in Github. If you select `CircleCI Checks` > `build_test_process`, you should see something like:

- `build` - Success
- `html-proofer` - Success
- `test` - Success
- `process` - Success

**Review by thisisdano — APPROVED** [review]

**Comment by thisisdano** [comment]
Preview link works now: https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/cms/events/2021/12/2021-12-21-overcoming-your-fear-of-data/

**Review by thisisdano — APPROVED** [review]

**Comment by thisisdano** [comment]
Fixed `Institute` → `Institutes`

**Pull request merged**
