### PR TITLE
Updates: Sara's Author page

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
updated GitHub, photo, location 
made visible

---

**Preview:**

### CODE REVIEW

**Comment by jeremyzilar** [comment]
I think @saracope already changed it this AM https://github.com/GSA/digitalgov.gov/pull/1929

**Comment by jeremyzilar** [comment]
@ToniBonittoGSA I see you changed a lot of the comment/helper text in this. Did you want me to update it globally for all the authors?

**Comment by ToniBonittoGSA** [comment]
@jeremyzilar these were diff. updates
I didn't change the helper text; some of it is different when we use the Workflow the copy & paste the edits

**Comment by saracope** [comment]
It looks like there aren't any new changes after doing the merge commit. Closing out. 

Thanks!

```
These merge commits were added into this branch cleanly.
There are no new changes to show.
```

**Pull request closed without merging**
