### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by Gabr1elleKING**
Updating - name is spelled incorrectly. Rachel, should be Rachael. Thanks

This PR implements the following **changes:**

*Updating - name is spelled incorrectly. Rachel, should be Rachael. Thanks

**[URL / Link to page](https://digital.gov/authors/dr-rachel-bradley-montgomery/)**

Preview Link is here: https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/Gabr1elleKING-patch-28/authors/dr-rachel-bradley-montgomery/

### CODE REVIEW

**Comment by Gabr1elleKING** [comment]
Good Morning @mejiaj. I am updating this author page as Dr. Rachael's name is spelled incorrectly. I made the updates, but i see that the slug is misspelled as well: rachel-bradley-montgomery. (https://digital.gov/authors/dr-rachel-bradley-montgomery/) should be rachael-bradley-montgomery. Toni is OOO and I am wondering if there is a way I can update the slug, or if I should delete this author entirely and create a new one?

**Comment by mejiaj** [comment]
@Gabr1elleKING not necessary to delete. 

We can update the author name and add an alias so the old name redirects. If there aren't that many links to the profile, we can just update the name. How would you like to proceed?

**Comment by Gabr1elleKING** [comment]
@mejiaj that is great! And there actually aren't any links to this profile yet (there will be two once I put up Plain Language Summit page) so I guess we can just proceed by updating the name only!

**Review by mejiaj — APPROVED** [review]

**Review by mejiaj — CHANGES_REQUESTED** [review]
Let's update the folder name as well.

**Comment by Gabr1elleKING** [comment]
New preview: https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/Gabr1elleKING-patch-28/authors/dr-rachel-bradley-montgomery/

**Comment by Gabr1elleKING** [comment]
@mejiaj thanks the preview is now showing the proper name thanks for making this change. I am not authorized to approve though, can you approve? : https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/Gabr1elleKING-patch-28/authors/dr-rachel-bradley-montgomery/

**Comment by Gabr1elleKING** [comment]
Thanks again @mejiaj . Once this builds I will add Ammie F. to review so she can merge, unless you are able (I don't have the ability to merge PRs)

**Review by afeijoo — APPROVED** [review]

**Review by mejiaj — APPROVED** [review]

**Pull request merged**
