### PR TITLE
Topics Removal: 3+ topics

### PR DESCRIPTION
**Pull request by clmedders**
## Summary

This PR will removed 3 or more topics that are needed. 

URLs have been added to Wayback Machine as well.

New topics number from 491 → 462.

### Preview

[Link to Preview](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/cm-3More-topics-removal/)

### Solution
remove both the topic along with where they are tagged throughout the site. 

### How To Test

1. Refer to the spreadsheet within the ticket titled `DG - Topics: Remove ROT topics` ensure that all files have been removed

---

### Dev Checklist

- [x] PR has correct labels
- [x] A11y testing (voice over testing, meets WCAG, run axe tools)
- [x] Code is formatted properly

### CODE REVIEW

**Comment by mejiaj** [comment]
@clmedders a few questions 

1. Were these topics added to the internet archive? If so, can we note that in the PR description?
1. Can we add the new count for topics from `/topics` landing? _Ex: `491 → 462`_

**Review by bonnieAcameron — DISMISSED** [review]
looks good! Thank you for catching small formatting updates as you go!

**Review by nick-mon1 — CHANGES_REQUESTED** [review]
>**Note**
>@mejiaj: This was addressed in [11dd083](https://github.com/GSA/digitalgov.gov/pull/6876/commits/11dd083b9bb42c6f00fcf03f257b0c916337e6c8). Updated this comment for clarity.

---

<details><summary>Unused topic (addressed)</summary>

<p></p>

29 topics are included for the following spreadsheet **Notes** column filter:

```
- 3 items tagged
- Agency tag; 3 items tagged
- Event tag; 3 items tagged.
- Program tag; 3 items tagged
- Program tag; 4 items tagged
- Jurisdiction tag; 3 items tagged.
- Program tag; 7 items tagged
```


But only 28 topics were removed in the PR:

1. blm
2. centers-for-medicare-and-medicaid-services
3. cio
4. cio-council
5. connect-gov
6. consumer-action-handbook
7. digital-services-playbook
8. eia
9. government-publishing-office
10. gpo
11. hiv-gov
12. imls
13. national-institute-of-allergy-and-infectious-diseases
14. **national-institute-of-justice** (need to remove)
15. ndu
16. nrc
17. occupational-safety-and-health-administration
18. office-of-the-director-of-national-intelligence
19. oip
20. onrr
21. skills
22. summit
23. technology-industry-day
24. the-bureau-of-land-management
25. tribal
26. united-states-air-force
27. us-energy-information-administration
28. us-forest-service
29. usajobs

Will need to remove the topic from the front matter from these files:

- `2014-12-10-data-visualization-challenge-using-open-data-to-reduce-crime.md`
- `2015-06-29-creating-a-social-media-report-that-matters.md`
- `2015-10-08-white-house-kicks-off-challenge-gov-anniversary-with-wealth-of-new-prize-competitions.md`

</details>

**Review by bonnieAcameron — APPROVED** [review]

**Review by mejiaj — APPROVED** [review]
All checks are passing, approved.

**Review by nick-mon1 — APPROVED** [review]
@clmedders Thanks for the topics clean up work!

**Review by ToniBonittoGSA — APPROVED** [review]

**Pull request merged**
