### PR TITLE
Update spanish-language-style-guide-and-glossaries.md

### PR DESCRIPTION
**Pull request by ToniBonittoGSA**
new copy from Laura

Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/ToniBonittoGSA-patch-2/resources/spanish-language-style-guide-and-glossaries/

### CODE REVIEW

**Comment by lggsa** [comment]
Hi Toni,
Not sure if this is the right place to comment, re: title of the page, I thought it would be Bilingual Glossaries, Dictionaries, And Style Guides.

The IRS glossaries need to be separated by language, one on each line - right now they are running as a paragraph.  They were all revised in August of 2018 so perhaps we can take that out of each line and add it to the description?
The Glossary of Tax Words and Phrases Used in Publications Issued by the IRS is currently available for download in six languages (all languages revised in August, 2018):

Environmental Protection Agency (EPA)  Please add "of"
The EPA’s Glosario ambiental bilingüe has a wealth **of** terminology, abbreviations and acronyms used by many of the EPA’s environmental programs.

San Francisco City and County   Please add "a"
The Translation Glossary page provides **a** link to download a Microsoft Excel.xlsx file for glossaries in three languages: Spanish, Vietnamese, and Filipino (Tagalog).

Let's talk about options to link to the USAGov bilingual style guide

I just picked up the description from the guide, perhaps you can include the link in the bolded text as you've done with the other resources? 
The Filipino Translation Style Guide
**The Filipino Translation Style Guide** provides guidelines for translation in the Filipino language for the City and County of San Francisco.

**Comment by ToniBonittoGSA** [comment]
Thanks, @lggsa! I'll take a look

**Comment by ToniBonittoGSA** [comment]
**_Note_**:
https://digital.gov/resources/spanish-language-style-guide-and-glossaries/ 
will need to redirect to this new page

**Comment by lggsa** [comment]
Hey Toni,

The page is looking really good!

I thought we could change the current text under USAGov Bilingual Style Guide to this and link the bold text instead of having a floating URL, what do you think?  Also, I added "of" before best practices.

USAGov 
The **USAGov Bilingual Style Guide** is a practical guide on the use of best practices to create bilingual digital content for USAGov and USAGov en Español. [https://www.usa.gov/style-guide/table-of-contents]

**Comment by ToniBonittoGSA** [comment]
got it, @lggsa 
should be live in a few

**Pull request merged**
