### PR TITLE
Fixing the Resource Page Design build

### PR DESCRIPTION
**Pull request by jeremyzilar**
There is a problem with the `resource-page-design` branch that I just pushed. The site is fine but it is not building on Federalist at the moment and it is not clear why. And there are no errors in the log. I am going to be looking into this locally.

### CODE REVIEW

**Comment by jeremyzilar** [comment]
## Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/

**Comment by jeremyzilar** [comment]
Ok. I think this is good to go.
Fixed the error that was stopping the build.
Also fixed an error with the way that months were displaying in the GitHub, Last Updated link on pages.

**Comment by jeremyzilar** [comment]
Here is a working example of the pages:
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/communities/
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/services/
https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/resources/

**Comment by thisisdano** [comment]
I realize this isn't part of this PR, and it should not hold up the PR, but I think there may be an issue using the `/` as a separator in the breadtrumb trail. It has a bit of an "either/or" connotation in 2-level trails, and a `>` may be less ambiguous, even if uglier. Worth testing

**Comment by thisisdano** [comment]
For later, but let's keep it in mind: spacing between service headers and the buttons above them results in an ambiguous stack. Totally even spacing flattens the hierarchy and we'll probably want to unflatten it.

- - -

screen shot 2017-12-08 at 11 32 47 am

**Comment by thisisdano** [comment]
@jeremyzilar Looks like something has messed up the columns in collections pages?

- - -

screen shot 2017-12-08 at 11 38 40 am

**Comment by jeremyzilar** [comment]
Yes, @thisisdano — all good points. Will address in future iterations of the page

**Comment by jeremyzilar** [comment]
Here is a preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/communities/

Collections page: https://federalist-proxy.app.cloud.gov/preview/gsa/digitalgov.gov/resource-page-design/categories/challenges/

**Pull request merged**
