### PR TITLE
DRAFT: New Tools and Services page with contact list

### PR DESCRIPTION
**Pull request by jeremyzilar**
This is a draft of the new Tools and Services page that includes a list of programs from around govt

---

> “As someone in OGP, I need to know who to contact in TTS about specific programs/products. I can look up their email in the Google Contacts so I only need their name.”

> “As a community lead, I need to know who runs which program/product in TTS, especially given the relatively high level of staff moves and turnover.”

**Doc:** https://docs.google.com/document/d/1wsMzKXr6pklZD5Wt2Dxs2Y9aQ2ADI5SXAcCJO4fJbpE/edit#

---

image

## Key things we've changed

- [x] **Featured Tools and Services** — this list of tools and services that product managers in the government need when modernizing their websites and digital services ([link](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/contact-us-page/services/))
  - there is a new layout for the cards that display each service
  - Each service now uses a single source for the service logo and icon
  - contact information is included in each service (currently only email is supported)
  - now authors are associated with services
- [x] **Directory of Services, Tools, and Teams** — this is a wider directory of services, tools, and teams that product managers in government  ([link](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/contact-us-page/services/))
  - Each service now uses a single source for the service logo and icon
  - contact information is included in each service (currently only email is supported)
  - now authors are associated with services
- [x] **Logos and Icons** — there is a new set of logos and icons for all of our services
  - there is logo file and icon file for each service that is smaller in size, better for performance
  - the whole site now uses these icons
- [x] **About page** — edited team and removed the contact us section in favor of a new page ([link](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/contact-us-page/about/))
- [x] **Contact us page** — there is a new contact us page ([link](https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/contact-us-page/about/))

---

**Preview: Featured Services**: https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/contact-us-page/services/
**Preview: Directory**: https://federalist-466b7d92-5da1-4208-974f-d61fd4348571.app.cloud.gov/preview/gsa/digitalgov.gov/contact-us-page/services/directory

### CODE REVIEW

**Comment by jeremyzilar** [comment]
@saracope — I started in on this, but I feel like I should pause and we should do this together. This touches on so many parts of the site and I feel like it would be a good thing for us to do together. Not sure if there is a time pressure around getting this up or not.
@afeijoo — can this wait a week till we are all in DC?

**Comment by afeijoo** [comment]
@jeremyzilar & @saracope It can wait; there isn't a hard, specific deadline.

**Comment by afeijoo** [comment]
The user stories reflect including program leads' names. Can they be added to the preview on the services page too?

**Comment by jeremyzilar** [comment]
@afeijoo @saracope @ToniBonittoGSA if instead of an email address, we included the people on the team?

Then you can click through to the person's profile OR the website to contact the right people?

image

**Comment by afeijoo** [comment]
Can it be both the team members names AND the general team email? Going to the website seems like extra, unnecessary steps to find a way to contact the team.

**Comment by jeremyzilar** [comment]
OK — Here is what I think we need do to get this up and then revise some more.

- Move the directory to a new page `/services/directory/`
- Link to the directory from the bottom of the services page and the contact page
- merge it in

This will allow us to send out the list to people in TTS and start getting their feedback. Also will help to answer the question, what is the difference between the list at the top, and the list at the bottom.

**Pull request merged**
